---
- name: restart rabbitmq
  service:
    name: rabbitmq-server
    state: restarted

- name: start rabbitmq
  service:
    name: rabbitmq-server
    state: started

- name: stop rabbitmq
  service:
    name: rabbitmq-server
    state: stopped
